default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: wolo

development:
  <<: *default
  database: hello_rails_app_production

test:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_App_test
  pool: 5
  username: postgres
  password: wolo

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
